### ISSUE TITLE
Some questions on partials & JS helpers

### ISSUE THREAD

**Issue by gracehlin** [james-andrewsmith/handlebars-net#11]
Hi @james-andrewsmith ,
 
I'm thinking about using your library for project and wanted to check a couple things which I wasn't clear on after reading the readme 

With your library can I:
• use partials?
• use helpers which execute javascript such as math or string manipulation?
• run other javascript libraries inside a template such as moment.js

Thanks! any insight or examples would be appreciated.

**Comment by james-andrewsmith** [comment]
Hi @gracehlin,

Good to hear you're interested! Apologies it's not better documented, it's something I've been trying to get to. 

Just to confirm you can: 
* Use Partials (with native syntax {{> partial/path/name}}
* Use custom helpers 
* Use external libraries (provided they play nice with ClearScript)

I actually have some examples with moment.js already in the repository. 

Moment.js Helpers Here
https://github.com/james-andrewsmith/handlebars-net/blob/feature/mono-proxy/src/Handlebars.Helper/Helper/format.date.js

See an example of how you can specify the external libraries here: 
https://github.com/james-andrewsmith/handlebars-net/blob/feature/mono-proxy/src/Handlebars.TestSuite/app.config

I'll try to publish a solid example to the ExampleBasic project using these elements to make it a little more obvious. 

I find this approach works really well for any project where you want to reuse the sample template on the server and client. 

James

**Comment by gracehlin** [comment]
Thank you so much @james-andrewsmith for the speedy reply! It's really helpful and I'm going to take a look at the examples now. You also mentioned in the readme that if we're deploying to Azure in a web role (which is what we're doing now), there's an example project ExampleAzureWebRole.csproj that we can look at. I can't seem to find it in the solution, is it renamed or removed? If so then no biggie I can try to figure it out using the MSDN link you provided. Thanks so much again for your help!

**Comment by james-andrewsmith** [comment]
No troubles @gracehlin!

I'm deploying to azure and it's actually a lot easier now (I should update the readme) since the switch to ClearScript, (Basdically it should "just work") if you do run into trouble just check: 

1. The CPU target of your app, I find specifying x64 instead of AnyCPU is easier. 
2. Install the C++ Runtime (see ClearScript site/docs/forums over at CodePlex https://clearscript.codeplex.com/)

**Comment by gracehlin** [comment]
Awesome @james-andrewsmith , thanks for your help!
